## Imports

In [22]:
import pandas as pd
import numpy as np
import ast
import re
import requests
import os
pd.set_option('display.max_rows', None)

# Chapter Data EDA/Cleaning

## How many chapters.csv

In [10]:
Chapterdf = pd.read_csv('../Data/How many chapters.csv')
Chapterdf.head()

,Chapter Number,Chapter Name,Chapter Image
0,Chapter 1,Jackson,https://img.game8.co/3252676/016d74f47a6920769...
1,Chapter 2,Seattle Day 1,https://img.game8.co/3252681/208e3bd72b0c4ce49...
2,Chapter 3,Seattle Day 2,https://img.game8.co/3252682/541861fadb8610c14...
3,Chapter 4,Seattle Day 3,https://img.game8.co/3255016/3fb74e357dc25e5e5...
4,Chapter 5,The Park,https://img.game8.co/3252680/68d10ee83ce0e2bad...

In [11]:
Chapterdf['Chapter Image'] = Chapterdf['Chapter Number'].apply(lambda x: f"Data/Images/chapter_images/Chapter {x.split(':')[0].split(' ')[1]}.jpg")
Chapterdf.head()

  Chapter Number   Chapter Name                             Chapter Image
0      Chapter 1        Jackson  Data/Images/chapter_images/Chapter 1.jpg
1      Chapter 2  Seattle Day 1  Data/Images/chapter_images/Chapter 2.jpg
2      Chapter 3  Seattle Day 2  Data/Images/chapter_images/Chapter 3.jpg
3      Chapter 4  Seattle Day 3  Data/Images/chapter_images/Chapter 4.jpg
4      Chapter 5       The Park  Data/Images/chapter_images/Chapter 5.jpg

In [45]:
Chapterdf.to_csv('Chapter information.csv', index=False)

## Chapter name with chapter section with main objectives

In [13]:
Chdf = pd.read_csv('../Data/Chapter name with chapter section with main objectives.csv')
Chdf.head()

,Chapter Number,Chapter Name,Chapter Section,Main Objective
0,Chapter 1,Jackson,Prologue,・Ride into town on horse・Play guitar as Joel
1,Chapter 1,Jackson,Waking Up,・Explore the town・Have a snowball fight
2,Chapter 1,Jackson,The Overlook,・Fight through the infected while learning combat
3,Chapter 1,Jackson,Patrol,"・Explore the patrol area, eliminating any infe..."
4,Chapter 1,Jackson,The Horde,"・Run from the infected, following behind Joel ..."

In [14]:
Chdf['Main Objective'] = Chdf['Main Objective'].str.replace('・', ', ').str.strip().str.lstrip(', ')
Chdf.head()

,Chapter Number,Chapter Name,Chapter Section,Main Objective
0,Chapter 1,Jackson,Prologue,"Ride into town on horse, Play guitar as Joel"
1,Chapter 1,Jackson,Waking Up,"Explore the town, Have a snowball fight"
2,Chapter 1,Jackson,The Overlook,Fight through the infected while learning combat
3,Chapter 1,Jackson,Patrol,"Explore the patrol area, eliminating any infec..."
4,Chapter 1,Jackson,The Horde,"Run from the infected, following behind Joel a..."

In [19]:
def format_main_objective_as_list(objectives_string):
    if isinstance(objectives_string, str) and objectives_string.strip():
        objectives_list = [obj.strip() for obj in objectives_string.split(',')]
        formatted_list = ""
        for i, objective in enumerate(objectives_list):
            if objective: 
                formatted_list += f"{i + 1}. {objective}\n"
        return formatted_list.strip() 
    else:
        return ""

In [20]:
Chdf['Main Objective'] = Chdf['Main Objective'].apply(format_main_objective_as_list)

Chdf.head()

,Chapter Number,Chapter Name,Chapter Section,Main Objective
0,Chapter 1,Jackson,Prologue,1. Ride into town on horse\n2. Play guitar as ...
1,Chapter 1,Jackson,Waking Up,1. Explore the town\n2. Have a snowball fight
2,Chapter 1,Jackson,The Overlook,1. Fight through the infected while learning c...
3,Chapter 1,Jackson,Patrol,1. Explore the patrol area\n2. eliminating any...
4,Chapter 1,Jackson,The Horde,1. Run from the infected\n2. following behind ...

In [21]:
Chdf.to_csv('Chapter and chapter section main objectives.csv', index=False)

## Chapter section walkthrough

In [16]:
Cwdf = pd.read_csv('../Data/Chapter section walkthrough.csv')
Cwdf.head()

,Chapter Name,Chapter Section,Section Walkthrough,Mission Tips and Strategy,Chapter Section Image
0,Jackson,Prologue,1. Follow Tommy all the way to town.\n2. Play ...,"**Playing Guitar**\nTo play guitar, push the c...",https://img.game8.co/3254598/6752f40e66a1fc1eb...
1,Jackson,Waking Up,1. Follow Jesse.\n2. Follow Jesse and Maria.\n...,**The Snowball Fight**\nMake a snowball by pic...,https://img.game8.co/3254599/3c820373f2db39162...
2,Jackson,The Overlook,1. Follow Owen\n2. After you and Owen split up...,**Using Listening Mode**\nListen Mode is one o...,https://img.game8.co/3254637/692d3d01b3030c2b6...
3,Jackson,Patrol,1. Follow Dina.\n2. After getting off your hor...,**Utilizing Stealth Kills**\nStealth kills are...,https://img.game8.co/3254638/e4bfa69a24601c619...
4,Jackson,The Horde,1. Run away from the horde of infected.\n2. Fo...,No mission tips and strategy found,https://img.game8.co/3254639/39dd93f96c55ae94e...

In [18]:
phrases_to_remove = [
    "How to Play Guitar",
    "How to Use Listen Mode",
    "How to Use Listening Mode",
    "How to Kill Shamblers",
    "If you're still having trouble with your picking, see the guide below! How to Play Guitar",
    "Trophy Guide | List of Trophies",
    "Crossbow: Location and Best Upgrades",
    "How to Kill The Rat King"
]

for phrase in phrases_to_remove:
    Cwdf['Mission Tips and Strategy'] = Cwdf['Mission Tips and Strategy'].str.replace(phrase, '', regex=False)

Cwdf['Mission Tips and Strategy'] = Cwdf['Mission Tips and Strategy'].str.replace(r'\*\*(.*?)\*\*', r'\1 - ', regex=True)


Cwdf.head()

,Chapter Name,Chapter Section,Section Walkthrough,Mission Tips and Strategy,Chapter Section Image
0,Jackson,Prologue,1. Follow Tommy all the way to town.\n2. Play ...,"Playing Guitar - \nTo play guitar, push the co...",https://img.game8.co/3254598/6752f40e66a1fc1eb...
1,Jackson,Waking Up,1. Follow Jesse.\n2. Follow Jesse and Maria.\n...,The Snowball Fight - \nMake a snowball by pick...,https://img.game8.co/3254599/3c820373f2db39162...
2,Jackson,The Overlook,1. Follow Owen\n2. After you and Owen split up...,Using Listening Mode - \nListen Mode is one of...,https://img.game8.co/3254637/692d3d01b3030c2b6...
3,Jackson,Patrol,1. Follow Dina.\n2. After getting off your hor...,Utilizing Stealth Kills - \nStealth kills are ...,https://img.game8.co/3254638/e4bfa69a24601c619...
4,Jackson,The Horde,1. Run away from the horde of infected.\n2. Fo...,No mission tips and strategy found,https://img.game8.co/3254639/39dd93f96c55ae94e...

In [30]:
def download_image(image_url, filename):
    target_directory = '../Data/Images/chapter_section_images'
    local_path = os.path.join(target_directory, f"{filename}.jpg")

    try:
        response = requests.get(image_url, stream=True, timeout=10)
        response.raise_for_status()

        with open(local_path, 'wb') as out_file:
            for chunk in response.iter_content(chunk_size=8192):
                out_file.write(chunk)

        print(f"Downloaded: {local_path}")
        return local_path

    except requests.exceptions.RequestException as e:
        print(f"Error downloading {image_url}: {e}")
        return None
    except IOError as e:
        print(f"Error saving image {local_path}: {e}")
        return None

In [31]:
for index, row in Cwdf.iterrows():
    image_url = row['Chapter Section Image']
    section_name = row['Chapter Section']
    download_image(image_url, section_name)

Error downloading ../Data/Images/chapter_section_images\Prologue.jpg: Invalid URL '../Data/Images/chapter_section_images\\Prologue.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\Prologue.jpg?
Error downloading ../Data/Images/chapter_section_images\Waking Up.jpg: Invalid URL '../Data/Images/chapter_section_images\\Waking Up.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\Waking Up.jpg?
Error downloading ../Data/Images/chapter_section_images\The Overlook.jpg: Invalid URL '../Data/Images/chapter_section_images\\The Overlook.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\The Overlook.jpg?
Error downloading ../Data/Images/chapter_section_images\Patrol.jpg: Invalid URL '../Data/Images/chapter_section_images\\Patrol.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\Patrol.jpg?
Error downloading ../Data/Images/chapter_section_images\The Horde.jpg: Invalid URL '../Data/Images/chapter_section_images\\The Horde.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\The Horde.jpg?
Error downloading ../Data/Images/chapter_section_images\The Chalet.jpg: Invalid URL '../Data/Images/chapter_section_images\\The Chalet.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\The Chalet.jpg?
Error downloading ../Data/Images/chapter_section_images\Packing Up.jpg: Invalid URL '../Data/Images/chapter_section_images\\Packing Up.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\Packing Up.jpg?
Error downloading ../Data/Images/chapter_section_images\The Gate.jpg: Invalid URL '../Data/Images/chapter_section_images\\The Gate.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\The Gate.jpg?
Error downloading ../Data/Images/chapter_section_images\Downtown.jpg: Invalid URL '../Data/Images/chapter_section_images\\Downtown.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\Downtown.jpg?
Error downloading ../Data/Images/chapter_section_images\Eastbrook Elementary.jpg: Invalid URL '../Data/Images/chapter_section_images\\Eastbrook Elementary.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\Eastbrook Elementary.jpg?
Error downloading ../Data/Images/chapter_section_images\Capitol Hill.jpg: Invalid URL '../Data/Images/chapter_section_images\\Capitol Hill.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\Capitol Hill.jpg?
Error downloading ../Data/Images/chapter_section_images\Channel 13.jpg: Invalid URL '../Data/Images/chapter_section_images\\Channel 13.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\Channel 13.jpg?
Error downloading ../Data/Images/chapter_section_images\The Tunnels.jpg: Invalid URL '../Data/Images/chapter_section_images\\The Tunnels.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\The Tunnels.jpg?
Error downloading ../Data/Images/chapter_section_images\The Theater.jpg: Invalid URL '../Data/Images/chapter_section_images\\The Theater.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\The Theater.jpg?
Error downloading ../Data/Images/chapter_section_images\The Birthday Gift.jpg: Invalid URL '../Data/Images/chapter_section_images\\The Birthday Gift.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\The Birthday Gift.jpg?
Error downloading ../Data/Images/chapter_section_images\Hillcrest.jpg: Invalid URL '../Data/Images/chapter_section_images\\Hillcrest.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\Hillcrest.jpg?
Error downloading ../Data/Images/chapter_section_images\Finding Strings.jpg: Invalid URL '../Data/Images/chapter_section_images\\Finding Strings.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\Finding Strings.jpg?
Error downloading ../Data/Images/chapter_section_images\The Seraphites.jpg: Invalid URL '../Data/Images/chapter_section_images\\The Seraphites.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\The Seraphites.jpg?
Error downloading ../Data/Images/chapter_section_images\St. Mary's Hospital.jpg: Invalid URL "../Data/Images/chapter_section_images\\St. Mary's Hospital.jpg": No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\St. Mary's Hospital.jpg?
Error downloading ../Data/Images/chapter_section_images\Road to the Aquarium.jpg: Invalid URL '../Data/Images/chapter_section_images\\Road to the Aquarium.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\Road to the Aquarium.jpg?
Error downloading ../Data/Images/chapter_section_images\The Flooded City.jpg: Invalid URL '../Data/Images/chapter_section_images\\The Flooded City.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\The Flooded City.jpg?
Error downloading ../Data/Images/chapter_section_images\Infiltration.jpg: Invalid URL '../Data/Images/chapter_section_images\\Infiltration.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\Infiltration.jpg?
Error downloading ../Data/Images/chapter_section_images\Tracking Lesson.jpg: Invalid URL '../Data/Images/chapter_section_images\\Tracking Lesson.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\Tracking Lesson.jpg?
Error downloading ../Data/Images/chapter_section_images\The Stadium.jpg: Invalid URL '../Data/Images/chapter_section_images\\The Stadium.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\The Stadium.jpg?
Error downloading ../Data/Images/chapter_section_images\On Foot.jpg: Invalid URL '../Data/Images/chapter_section_images\\On Foot.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\On Foot.jpg?
Error downloading ../Data/Images/chapter_section_images\The Forward Base.jpg: Invalid URL '../Data/Images/chapter_section_images\\The Forward Base.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\The Forward Base.jpg?
Error downloading ../Data/Images/chapter_section_images\The Aquarium.jpg: Invalid URL '../Data/Images/chapter_section_images\\The Aquarium.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\The Aquarium.jpg?
Error downloading ../Data/Images/chapter_section_images\Hostile Territory.jpg: Invalid URL '../Data/Images/chapter_section_images\\Hostile Territory.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\Hostile Territory.jpg?
Error downloading ../Data/Images/chapter_section_images\Winter Visit.jpg: Invalid URL '../Data/Images/chapter_section_images\\Winter Visit.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\Winter Visit.jpg?
Error downloading ../Data/Images/chapter_section_images\The Forest.jpg: Invalid URL '../Data/Images/chapter_section_images\\The Forest.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\The Forest.jpg?
Error downloading ../Data/Images/chapter_section_images\The Coast.jpg: Invalid URL '../Data/Images/chapter_section_images\\The Coast.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\The Coast.jpg?
Error downloading ../Data/Images/chapter_section_images\Return to the Coast.jpg: Invalid URL '../Data/Images/chapter_section_images\\Return to the Coast.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\Return to the Coast.jpg?
Error downloading ../Data/Images/chapter_section_images\The Shortcut.jpg: Invalid URL '../Data/Images/chapter_section_images\\The Shortcut.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\The Shortcut.jpg?
Error downloading ../Data/Images/chapter_section_images\The Descent.jpg: Invalid URL '../Data/Images/chapter_section_images\\The Descent.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\The Descent.jpg?
Error downloading ../Data/Images/chapter_section_images\Ground Zero.jpg: Invalid URL '../Data/Images/chapter_section_images\\Ground Zero.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\Ground Zero.jpg?
Error downloading ../Data/Images/chapter_section_images\Return to the Aquarium.jpg: Invalid URL '../Data/Images/chapter_section_images\\Return to the Aquarium.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\Return to the Aquarium.jpg?
Error downloading ../Data/Images/chapter_section_images\The Marina.jpg: Invalid URL '../Data/Images/chapter_section_images\\The Marina.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\The Marina.jpg?
Error downloading ../Data/Images/chapter_section_images\The Island.jpg: Invalid URL '../Data/Images/chapter_section_images\\The Island.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\The Island.jpg?
Error downloading ../Data/Images/chapter_section_images\The Escape.jpg: Invalid URL '../Data/Images/chapter_section_images\\The Escape.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\The Escape.jpg?
Error downloading ../Data/Images/chapter_section_images\The Confrontation.jpg: Invalid URL '../Data/Images/chapter_section_images\\The Confrontation.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\The Confrontation.jpg?
Error downloading ../Data/Images/chapter_section_images\The Farm.jpg: Invalid URL '../Data/Images/chapter_section_images\\The Farm.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\The Farm.jpg?
Error downloading ../Data/Images/chapter_section_images\2425 Constance.jpg: Invalid URL '../Data/Images/chapter_section_images\\2425 Constance.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\2425 Constance.jpg?
Error downloading ../Data/Images/chapter_section_images\Pushing Inland.jpg: Invalid URL '../Data/Images/chapter_section_images\\Pushing Inland.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\Pushing Inland.jpg?
Error downloading ../Data/Images/chapter_section_images\The Resort.jpg: Invalid URL '../Data/Images/chapter_section_images\\The Resort.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\The Resort.jpg?
Error downloading ../Data/Images/chapter_section_images\The Beach.jpg: Invalid URL '../Data/Images/chapter_section_images\\The Beach.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\The Beach.jpg?
Error downloading ../Data/Images/chapter_section_images\Epilogue.jpg: Invalid URL '../Data/Images/chapter_section_images\\Epilogue.jpg': No scheme supplied. Perhaps you meant https://../Data/Images/chapter_section_images\Epilogue.jpg?

In [33]:
for index, row in Cwdf.iterrows():
    image_url = row['Chapter Section Image']
    section_name = row['Chapter Section']
    local_path = os.path.join('../Data/Images/chapter_section_images', f"{section_name}.jpg")
    normalized_path = local_path.replace('\\', '/')
    Cwdf.loc[index, 'Chapter Section Image'] = normalized_path

Cwdf.head()

,Chapter Name,Chapter Section,Section Walkthrough,Mission Tips and Strategy,Chapter Section Image
0,Jackson,Prologue,1. Follow Tommy all the way to town.\n2. Play ...,"Playing Guitar - \nTo play guitar, push the co...",../Data/Images/chapter_section_images/Prologue...
1,Jackson,Waking Up,1. Follow Jesse.\n2. Follow Jesse and Maria.\n...,The Snowball Fight - \nMake a snowball by pick...,../Data/Images/chapter_section_images/Waking U...
2,Jackson,The Overlook,1. Follow Owen\n2. After you and Owen split up...,Using Listening Mode - \nListen Mode is one of...,../Data/Images/chapter_section_images/The Over...
3,Jackson,Patrol,1. Follow Dina.\n2. After getting off your hor...,Utilizing Stealth Kills - \nStealth kills are ...,../Data/Images/chapter_section_images/Patrol.jpg
4,Jackson,The Horde,1. Run away from the horde of infected.\n2. Fo...,No mission tips and strategy found,../Data/Images/chapter_section_images/The Hord...

In [34]:
Cwdf.to_csv('Chapter section walkthrough with mission tips and strategy and chapter section images.csv', index=False)

# Enemies EDA/Cleaning

In [37]:
enemy_df = pd.read_csv('../Data/Enemies.csv')

enemy_df.head()

,Enemy Name,Enemy Image URL,Description,How to Kill URL,How to Kill Guide
0,Runners,https://img.game8.co/3252326/b28115a05f1fe7505...,Runners are the most common enemy in The Last ...,https://game8.co/games/Last-of-Us-2/archives/2...,"{'How to Kill Runners': [{'type': 'paragraph',..."
1,Stalkers,https://img.game8.co/3252515/e72f76b3a6874dec3...,Stalkers are the next stage of infected after ...,https://game8.co/games/Last-of-Us-2/archives/2...,{'How to Kill Stalkers': [{'type': 'paragraph'...
2,Clickers,https://img.game8.co/3252055/472aa08fcbf0ce14b...,"Clickers are completely blind, thus there is n...",https://game8.co/games/Last-of-Us-2/archives/2...,{'How to Kill Clickers': [{'type': 'paragraph'...
3,Bloaters,https://img.game8.co/3252524/439c652f79f7543be...,"Bloaters are a late stage of infected, are ext...",https://game8.co/games/Last-of-Us-2/archives/2...,{'How to Kill Bloaters': [{'type': 'paragraph'...
4,Shamblers,https://img.game8.co/3252325/bedcc8bb79b5be7c4...,The shambler is a new type of powerful infecte...,https://game8.co/games/Last-of-Us-2/archives/2...,{'How to Kill Shamblers': [{'type': 'paragraph...

In [38]:
enemy_df = enemy_df.rename(columns={
    'Enemy Image URL': 'Enemy Image',
    'Description': 'Enemy Description',
    'How to Kill Guide': 'How To Kill Enemy'
}).drop(columns=['How to Kill URL'])

enemy_df.head()

,Enemy Name,Enemy Image,Enemy Description,How To Kill Enemy
0,Runners,https://img.game8.co/3252326/b28115a05f1fe7505...,Runners are the most common enemy in The Last ...,"{'How to Kill Runners': [{'type': 'paragraph',..."
1,Stalkers,https://img.game8.co/3252515/e72f76b3a6874dec3...,Stalkers are the next stage of infected after ...,{'How to Kill Stalkers': [{'type': 'paragraph'...
2,Clickers,https://img.game8.co/3252055/472aa08fcbf0ce14b...,"Clickers are completely blind, thus there is n...",{'How to Kill Clickers': [{'type': 'paragraph'...
3,Bloaters,https://img.game8.co/3252524/439c652f79f7543be...,"Bloaters are a late stage of infected, are ext...",{'How to Kill Bloaters': [{'type': 'paragraph'...
4,Shamblers,https://img.game8.co/3252325/bedcc8bb79b5be7c4...,The shambler is a new type of powerful infecte...,{'How to Kill Shamblers': [{'type': 'paragraph...

In [41]:
def update_enemy_image_url(row):
    enemy_name = row['Enemy Name']
    image_path = f"../Data/Images/enemy_images/{enemy_name}.jpeg"
    return image_path

enemy_df['Enemy Image'] = enemy_df.apply(update_enemy_image_url, axis=1)

enemy_df.head()

,Enemy Name,Enemy Image,Enemy Description,How To Kill Enemy
0,Runners,../Data/Images/enemy_images/Runners.jpeg,Runners are the most common enemy in The Last ...,"{'How to Kill Runners': [{'type': 'paragraph',..."
1,Stalkers,../Data/Images/enemy_images/Stalkers.jpeg,Stalkers are the next stage of infected after ...,{'How to Kill Stalkers': [{'type': 'paragraph'...
2,Clickers,../Data/Images/enemy_images/Clickers.jpeg,"Clickers are completely blind, thus there is n...",{'How to Kill Clickers': [{'type': 'paragraph'...
3,Bloaters,../Data/Images/enemy_images/Bloaters.jpeg,"Bloaters are a late stage of infected, are ext...",{'How to Kill Bloaters': [{'type': 'paragraph'...
4,Shamblers,../Data/Images/enemy_images/Shamblers.jpeg,The shambler is a new type of powerful infecte...,{'How to Kill Shamblers': [{'type': 'paragraph...

In [42]:
def extract_how_to_kill_text(guide_data_str):
    extracted_text = ""
    try:
        guide_data = ast.literal_eval(guide_data_str)

        if isinstance(guide_data, dict):
            for key, value in guide_data.items():
                if isinstance(value, list):
                    for item in value:
                        if isinstance(item, dict) and item.get('type') == 'paragraph' and 'content' in item:
                            extracted_text += item['content'] + " " 

    except (ValueError, SyntaxError) as e:
        print(f"Error evaluating guide data: {e}")
        return "" 

    return extracted_text.strip()

In [43]:
enemy_df['How To Kill Enemy'] = enemy_df['How To Kill Enemy'].apply(extract_how_to_kill_text)
enemy_df.head()

,Enemy Name,Enemy Image,Enemy Description,How To Kill Enemy
0,Runners,../Data/Images/enemy_images/Runners.jpeg,Runners are the most common enemy in The Last ...,Fighting against Runners will happen frequentl...
1,Stalkers,../Data/Images/enemy_images/Stalkers.jpeg,Stalkers are the next stage of infected after ...,Stalkers are the more evolved stage of the inf...
2,Clickers,../Data/Images/enemy_images/Clickers.jpeg,"Clickers are completely blind, thus there is n...",Clickers can be easily dealt with by instantly...
3,Bloaters,../Data/Images/enemy_images/Bloaters.jpeg,"Bloaters are a late stage of infected, are ext...","Bloaters are the massive, heavy-hitting varian..."
4,Shamblers,../Data/Images/enemy_images/Shamblers.jpeg,The shambler is a new type of powerful infecte...,Shamblers are large infected creatures that yo...

In [44]:
enemy_df.to_csv('Enemy information.csv', index=False)

# Weapon EDA/Cleaning

In [53]:
weapon_df = pd.read_csv('../Data/Weapons.csv')

weapon_df.head()

,Weapon Category,Weapon Name,Weapon Link,Weapon Icon URL,Description,Location
0,Handguns,Semi-Auto Pistol,https://game8.co/games/Last-of-Us-2/archives/2...,https://img.game8.co/3252180/ec9f8dd1d23c44108...,Short-range handgun with high fire rate and mo...,Obtained by default in Jackson - Waking Up.
1,Handguns,Revolver,https://game8.co/games/Last-of-Us-2/archives/2...,https://img.game8.co/3252178/aa7459e5b5f413b88...,Mid-range revolver with moderate damage and sl...,Get from the box upstairs in Jackson - Packing...
2,Handguns,Military Pistol,https://game8.co/games/Last-of-Us-2/archives/2...,https://img.game8.co/3252528/85a7ba460f685c0ad...,Short-range handgun with high fire rate and mo...,Obtain automatically in Seattle Day 1 - The St...
3,Handguns,Hunting Pistol,https://game8.co/games/Last-of-Us-2/archives/2...,https://img.game8.co/3252556/81bdd2a352fe591a5...,Long-range handgun with high damage and slow r...,Seattle Day 1 - On Foot (Safe)
4,Long Guns,Bolt-Action Rifle,https://game8.co/games/Last-of-Us-2/archives/2...,https://img.game8.co/3252179/a9a804ab28bafba79...,Long-range rifle with high damage and slow fir...,Obtained by default in Jackson - Waking Up.

In [54]:
weapon_df = weapon_df.rename(columns={
    'Weapon Icon URL': 'Weapon Image',
    'Description': 'Weapon Description',
    'Location': 'Weapon Location'
}).drop(columns=['Weapon Link'])

weapon_df.head()

,Weapon Category,Weapon Name,Weapon Image,Weapon Description,Weapon Location
0,Handguns,Semi-Auto Pistol,https://img.game8.co/3252180/ec9f8dd1d23c44108...,Short-range handgun with high fire rate and mo...,Obtained by default in Jackson - Waking Up.
1,Handguns,Revolver,https://img.game8.co/3252178/aa7459e5b5f413b88...,Mid-range revolver with moderate damage and sl...,Get from the box upstairs in Jackson - Packing...
2,Handguns,Military Pistol,https://img.game8.co/3252528/85a7ba460f685c0ad...,Short-range handgun with high fire rate and mo...,Obtain automatically in Seattle Day 1 - The St...
3,Handguns,Hunting Pistol,https://img.game8.co/3252556/81bdd2a352fe591a5...,Long-range handgun with high damage and slow r...,Seattle Day 1 - On Foot (Safe)
4,Long Guns,Bolt-Action Rifle,https://img.game8.co/3252179/a9a804ab28bafba79...,Long-range rifle with high damage and slow fir...,Obtained by default in Jackson - Waking Up.

In [55]:
def update_weapon_image_url(row):
    weapon_name = row['Weapon Name']
    image_path = f"../Data/Images/weapon_images/{weapon_name}.jpg"
    return image_path

weapon_df['Weapon Image'] = weapon_df.apply(update_weapon_image_url, axis=1)
weapon_df.head()

,Weapon Category,Weapon Name,Weapon Image,Weapon Description,Weapon Location
0,Handguns,Semi-Auto Pistol,../Data/Images/weapon_images/Semi-Auto Pistol.jpg,Short-range handgun with high fire rate and mo...,Obtained by default in Jackson - Waking Up.
1,Handguns,Revolver,../Data/Images/weapon_images/Revolver.jpg,Mid-range revolver with moderate damage and sl...,Get from the box upstairs in Jackson - Packing...
2,Handguns,Military Pistol,../Data/Images/weapon_images/Military Pistol.jpg,Short-range handgun with high fire rate and mo...,Obtain automatically in Seattle Day 1 - The St...
3,Handguns,Hunting Pistol,../Data/Images/weapon_images/Hunting Pistol.jpg,Long-range handgun with high damage and slow r...,Seattle Day 1 - On Foot (Safe)
4,Long Guns,Bolt-Action Rifle,../Data/Images/weapon_images/Bolt-Action Rifle...,Long-range rifle with high damage and slow fir...,Obtained by default in Jackson - Waking Up.

## Character EDA/Cleaning

In [56]:
character_df = pd.read_csv('../Data/Characters.csv')
character_df.head()

,Character Name,Character Icon URL,Character Main Image URL,Profile URL,Character Info
0,Ellie,https://img.game8.co/3253990/a38ae26121b6dd4dd...,https://img.game8.co/3253674/d94845ae35742fb7a...,https://game8.co/games/Last-of-Us-2/archives/2...,{'Ellie: Character Information': {'paragraphs'...
1,Joel,https://img.game8.co/3253992/2dca693d4b0e9c6b1...,https://img.game8.co/3253664/103b20839a9d395c4...,https://game8.co/games/Last-of-Us-2/archives/2...,{'Joel: Character Information': {'paragraphs':...
2,Dina,https://img.game8.co/3253995/6a10facf9fdc19b06...,https://img.game8.co/3253702/457134b322ef240fb...,https://game8.co/games/Last-of-Us-2/archives/2...,{'Dina: Character Information': {'paragraphs':...
3,Abby,https://img.game8.co/3254001/77d11f17280b8bcf5...,https://img.game8.co/3253680/e37a8d8fc6ff287db...,https://game8.co/games/Last-of-Us-2/archives/2...,{'Abby: Character Information': {'paragraphs':...
4,Yara,https://img.game8.co/3254016/e921679aa5dfbf1e7...,https://img.game8.co/3253753/a53e019404ad3d253...,https://game8.co/games/Last-of-Us-2/archives/2...,{'Yara: Character Information': {'paragraphs':...

In [57]:
character_df['Character Main Image URL'] = character_df['Character Name'].apply(lambda x: f"Data/Images/character_images/{x} icon.jpeg")


character_df = character_df.rename(columns={
    'Character Main Image URL': 'Character Image',
    'Character Info': 'Character Information'
}).drop(columns=['Character Icon URL', 'Profile URL'])

character_df.head()

,Character Name,Character Image,Character Information
0,Ellie,Data/Images/character_images/Ellie icon.jpeg,{'Ellie: Character Information': {'paragraphs'...
1,Joel,Data/Images/character_images/Joel icon.jpeg,{'Joel: Character Information': {'paragraphs':...
2,Dina,Data/Images/character_images/Dina icon.jpeg,{'Dina: Character Information': {'paragraphs':...
3,Abby,Data/Images/character_images/Abby icon.jpeg,{'Abby: Character Information': {'paragraphs':...
4,Yara,Data/Images/character_images/Yara icon.jpeg,{'Yara: Character Information': {'paragraphs':...

In [79]:
character_info_df = pd.DataFrame({
    'Character name': character_df['Character Name'],
    'Character Image': character_df['Character Image']
})
character_info_df['Basic Information'] = ''
character_info_df['Profile and Backstory'] = ''
character_info_df['What happens to the character'] = ''

In [80]:
character_info_df

,Character name,Character Image,Basic Information,Profile and Backstory,What happens to the character
0,Ellie,Data/Images/character_images/Ellie icon.jpeg,,,
1,Joel,Data/Images/character_images/Joel icon.jpeg,,,
2,Dina,Data/Images/character_images/Dina icon.jpeg,,,
3,Abby,Data/Images/character_images/Abby icon.jpeg,,,
4,Yara,Data/Images/character_images/Yara icon.jpeg,,,
5,Nora,Data/Images/character_images/Nora icon.jpeg,,,
6,Lev,Data/Images/character_images/Lev icon.jpeg,,,
7,Emily,Data/Images/character_images/Emily icon.jpeg,,,
8,Jesse,Data/Images/character_images/Jesse icon.jpeg,,,
9,Tommy,Data/Images/character_images/Tommy icon.jpeg,,,
10,Seth,Data/Images/character_images/Seth icon.jpeg,,,
11,Mel,Data/Images/character_images/Mel icon.jpeg,,,
12,Owen,Data/Images/character_images/Owen icon.jpeg,,,
13,Manny,Data/Images/character_images/Manny icon.jpeg,,,
14,Jordan,Data/Images/character_images/Jordan icon.jpeg,,,
15,Nick,Data/Images/character_images/Nick icon.jpeg,,,
16,Alice,Data/Images/character_images/Alice icon.jpeg,,,
17,Maria,Data/Images/character_images/Maria icon.jpeg,,,
18,Jerry,Data/Images/character_images/Jerry icon.jpeg,,,
19,Whitney,Data/Images/character_images/Whitney icon.jpeg,,,
20,Isaac,Data/Images/character_images/Isaac icon.jpeg,,,

In [81]:
def populate_basic_information(character_name, character_df, character_info_df):
    character_data_row = character_df[character_df['Character Name'] == character_name]

    if not character_data_row.empty and 'Character Information' in character_data_row.columns:
        character_info_data = character_data_row['Character Information'].iloc[0]

    
        if isinstance(character_info_data, str):
            try:
                character_info_data = ast.literal_eval(character_info_data)
            except (ValueError, SyntaxError) as e:
                print(f"Could not eval character_info for {character_name}: {e}")
                character_info_data = {} 


        if isinstance(character_info_data, dict) and 'Basic Information' in character_info_data:
            basic_info_content = character_info_data['Basic Information']

 
            if isinstance(basic_info_content, dict) and 'tables' in basic_info_content:
                table_list = basic_info_content['tables']

         
                if isinstance(table_list, list) and table_list:
               
                     table_item = table_list[0]

               
                     if isinstance(table_item, dict) and 'table_data' in table_item:
                        table_data = table_item['table_data']
  
                        basic_info_str = ""
                        for row_data in table_data:
 
                             for key, value in row_data.items():

                                  basic_info_str += f"{value.strip()}; "


                        new_basic_info_keys = ['Age', 'Status', 'Occupation', 'Role', 'Voice Actor']
                        extracted_values = [v.strip() for v in basic_info_str.strip('; ').split(';')]

                        if len(extracted_values) == len(new_basic_info_keys):

                            formatted_basic_info_parts = []
                            for i in range(len(new_basic_info_keys)):
                                formatted_basic_info_parts.append(f"{new_basic_info_keys[i]}: {extracted_values[i]}")

                            formatted_basic_info = ", ".join(formatted_basic_info_parts)


                            char_info_index = character_info_df[character_info_df['Character name'] == character_name].index
                            if not char_info_index.empty:
                                character_info_df.loc[char_info_index[0], 'Basic Information'] = formatted_basic_info
                                print(f"Basic Information for {character_name} populated successfully.")
                            else:
                                print(f"{character_name}'s row not found in character_info_df DataFrame.")
                        else:
                            print(f"Warning: Number of extracted values ({len(extracted_values)}) does not match number of keys ({len(new_basic_info_keys)}) for {character_name}. Basic Information not reformatted with new keys.")
                            char_info_index = character_info_df[character_info_df['Character name'] == character_name].index
                            if not char_info_index.empty:
                                 character_info_df.loc[char_info_index[0], 'Basic Information'] = basic_info_str.strip('; ')
                                 print(f"Basic Information for {character_name} populated with raw extracted values.")
                            else:
                                 print(f"{character_name}'s row not found in character_info_df DataFrame.")


                     else:
                        print(f"Basic Information for {character_name}: Expected table_data key not found in table item.")

            elif isinstance(basic_info_content, dict) and 'paragraphs' in basic_info_content and basic_info_content['paragraphs']:
                 char_info_index = character_info_df[character_info_df['Character name'] == character_name].index
                 if not char_info_index.empty:
                     character_info_df.loc[char_info_index[0], 'Basic Information'] = basic_info_content['paragraphs']
                     print(f"Basic Information (paragraph data) for {character_name} populated successfully.")
                 else:
                     print(f"{character_name}'s row not found in character_info_df DataFrame.")
            else:
                print(f"Basic Information for {character_name} contains an unexpected structure (not tables or paragraphs).")
        else:
            print(f"Basic Information heading not found in {character_name}'s Character Info dictionary or dictionary is empty.")
    else:
        print(f"{character_name}'s row or 'Character Info' column not found in character_df DataFrame.")

In [82]:
for character_name in character_info_df['Character name']:
    populate_basic_information(character_name, character_df, character_info_df)

character_info_df.head()

Basic Information for Ellie populated successfully.
Basic Information for Joel populated successfully.
Basic Information for Dina populated successfully.
Basic Information for Abby populated successfully.
Basic Information for Yara populated successfully.
Basic Information for Nora populated successfully.
Basic Information for Lev populated successfully.
Basic Information for Emily populated successfully.
Warning: Number of extracted values (3) does not match number of keys (5) for Jesse. Basic Information not reformatted with new keys.
Basic Information for Jesse populated with raw extracted values.
Basic Information for Tommy populated successfully.
Basic Information for Seth populated successfully.
Basic Information for Mel populated successfully.
Basic Information for Owen populated successfully.
Warning: Number of extracted values (4) does not match number of keys (5) for Manny. Basic Information not reformatted with new keys.
Basic Information for Manny populated with raw extracted values.
Warning: Number of extracted values (3) does not match number of keys (5) for Jordan. Basic Information not reformatted with new keys.
Basic Information for Jordan populated with raw extracted values.
Warning: Number of extracted values (3) does not match number of keys (5) for Nick. Basic Information not reformatted with new keys.
Basic Information for Nick populated with raw extracted values.
Basic Information for Alice populated successfully.
Warning: Number of extracted values (3) does not match number of keys (5) for Maria. Basic Information not reformatted with new keys.
Basic Information for Maria populated with raw extracted values.
Warning: Number of extracted values (3) does not match number of keys (5) for Jerry. Basic Information not reformatted with new keys.
Basic Information for Jerry populated with raw extracted values.
Warning: Number of extracted values (3) does not match number of keys (5) for Whitney. Basic Information not reformatted with new keys.
Basic Information for Whitney populated with raw extracted values.
Basic Information for Isaac populated successfully.

,Character name,Character Image,Basic Information,Profile and Backstory,What happens to the character
0,Ellie,Data/Images/character_images/Ellie icon.jpeg,"Age: 19, Status: Alive, Occupation: Jackson Pa...",,
1,Joel,Data/Images/character_images/Joel icon.jpeg,"Age: Mid 50's, Status: Deceased, Occupation: J...",,
2,Dina,Data/Images/character_images/Dina icon.jpeg,Age: Likely the same age as Ellie (19-21 yrs. ...,,
3,Abby,Data/Images/character_images/Abby icon.jpeg,"Age: Early Twenties, Status: Alive, Occupation...",,
4,Yara,Data/Images/character_images/Yara icon.jpeg,"Age: 16, Status: Deceased, Occupation: Former ...",,

for jesse,manny,jordan,nick,maria,jerry,whitney their data needs chainging to :

jesse:
Age:	Unknown
Occupation:	Jackson Patrol
Role:	Support Character
Voice Actor:	Stephen Chang

Manny:
Name:	Manny Alvarez
Age:	Unkown
Occupation:	WLF Combatant
Role:	Supporting Character
Voice Actor:	Alejandro Edda

Jordan:
Age:	Unknown
Occupation:	WLF Combatant
Role:	Supporting Character
Voice Actor:	Chase Austin

Nick:
Age:	Unknown
Occupation:	WLF Combatant
Role:	Supporting Character
Voice Actor:	None

Maria:
Age:	Unknown
Occupation:	Jackson Leader
Role:	Supporting Character
Voice Actor:	Ashley Scott


Jerry:
Age:	Unknown
Occupation:	Doctor
Role:	Supporting Character
Voice Actor:	Derek Phillips


Whitney:

Age:	Unknown
Occupation:	WLF Combatant
Role:	Supporting Character
Voice Actor:	Maggie Macdonald

In [83]:
corrected_basic_info = {
    'Jesse': """Age: Unknown
Occupation: Jackson Patrol
Role: Support Character
Voice Actor: Stephen Chang""",

    'Manny': """Name: Manny Alvarez
Age: Unkown
Occupation: WLF Combatant
Role: Supporting Character
Voice Actor: Alejandro Edda""",

    'Jordan': """Age: Unknown
Occupation: WLF Combatant
Role: Supporting Character
Voice Actor: Chase Austin""",

    'Nick': """Age: Unknown
Occupation: WLF Combatant
Role: Supporting Character
Voice Actor: None""",

    'Maria': """Age: Unknown
Occupation: Jackson Leader
Role: Supporting Character
Voice Actor: Ashley Scott""",

    'Jerry': """Age: Unknown
Occupation: Doctor
Role: Supporting Character
Voice Actor: Derek Phillips""",

    'Whitney': """Age: Unknown
Occupation: WLF Combatant
Role: Supporting Character
Voice Actor: Maggie Macdonald"""
}


for character_name, info_string in corrected_basic_info.items():
    char_index = character_info_df[character_info_df['Character name'] == character_name].index


    if not char_index.empty:
        character_info_df.loc[char_index[0], 'Basic Information'] = info_string.strip()
        print(f"Updated Basic Information for {character_name}")
    else:
        print(f"Warning: Could not find {character_name} in character_info DataFrame to update.")

character_info_df.head()

Updated Basic Information for Jesse
Updated Basic Information for Manny
Updated Basic Information for Jordan
Updated Basic Information for Nick
Updated Basic Information for Maria
Updated Basic Information for Jerry
Updated Basic Information for Whitney

,Character name,Character Image,Basic Information,Profile and Backstory,What happens to the character
0,Ellie,Data/Images/character_images/Ellie icon.jpeg,"Age: 19, Status: Alive, Occupation: Jackson Pa...",,
1,Joel,Data/Images/character_images/Joel icon.jpeg,"Age: Mid 50's, Status: Deceased, Occupation: J...",,
2,Dina,Data/Images/character_images/Dina icon.jpeg,Age: Likely the same age as Ellie (19-21 yrs. ...,,
3,Abby,Data/Images/character_images/Abby icon.jpeg,"Age: Early Twenties, Status: Alive, Occupation...",,
4,Yara,Data/Images/character_images/Yara icon.jpeg,"Age: 16, Status: Deceased, Occupation: Former ...",,

In [84]:
def populate_profile_and_backstory(character_name, character_df, character_info_df):

    character_data_row = character_df[character_df['Character Name'] == character_name]


    if not character_data_row.empty and 'Character Information' in character_data_row.columns:
        character_info_data = character_data_row['Character Information'].iloc[0]

       
        if isinstance(character_info_data, str):
            try:
                character_info_data = ast.literal_eval(character_info_data)
            except (ValueError, SyntaxError) as e:
                print(f"Could not evaluate character_info string for {character_name}: {e}")
                character_info_data = {} 

  
        if isinstance(character_info_data, dict) and 'Profile and Backstory' in character_info_data:
            profile_backstory_content = character_info_data['Profile and Backstory'] 

           
            if isinstance(profile_backstory_content, dict) and 'paragraphs' in profile_backstory_content and profile_backstory_content['paragraphs']:
                 profile_and_backstory_text = profile_backstory_content['paragraphs']

                 
                 char_info_index = character_info_df[character_info_df['Character name'] == character_name].index
                 if not char_info_index.empty:
                     character_info_df.loc[char_info_index[0], 'Profile and Backstory'] = profile_and_backstory_text
                     print(f"Profile and Backstory for {character_name} populated successfully.")
                 else:
                     print(f"{character_name}'s row not found in character_info_df DataFrame.")
            else:
                print(f"Profile and Backstory for {character_name} contains an unexpected structure (not paragraphs).")
        else:
            print(f"Profile and Backstory heading not found in {character_name}'s Character Info dictionary or dictionary is empty.")
    else:
        print(f"{character_name}'s row or 'Character Info' column not found in character_df DataFrame.")

In [85]:
for character_name in character_info_df['Character name']:
    populate_profile_and_backstory(character_name, character_df, character_info_df)

character_info_df.head()

Profile and Backstory for Ellie populated successfully.
Profile and Backstory for Joel populated successfully.
Profile and Backstory for Dina populated successfully.
Profile and Backstory for Abby populated successfully.
Profile and Backstory for Yara populated successfully.
Profile and Backstory for Nora populated successfully.
Profile and Backstory for Lev populated successfully.
Profile and Backstory for Emily populated successfully.
Profile and Backstory for Jesse populated successfully.
Profile and Backstory for Tommy populated successfully.
Profile and Backstory for Seth populated successfully.
Profile and Backstory for Mel populated successfully.
Profile and Backstory for Owen populated successfully.
Profile and Backstory for Manny populated successfully.
Profile and Backstory for Jordan populated successfully.
Profile and Backstory for Nick populated successfully.
Profile and Backstory for Alice populated successfully.
Profile and Backstory for Maria populated successfully.
Profile and Backstory for Jerry populated successfully.
Profile and Backstory for Whitney populated successfully.
Profile and Backstory for Isaac populated successfully.

,Character name,Character Image,Basic Information,Profile and Backstory,What happens to the character
0,Ellie,Data/Images/character_images/Ellie icon.jpeg,"Age: 19, Status: Alive, Occupation: Jackson Pa...","In The Last of Us 1, Ellie is immune to the Co...",
1,Joel,Data/Images/character_images/Joel icon.jpeg,"Age: Mid 50's, Status: Deceased, Occupation: J...","During the events of the first game, Joel emba...",
2,Dina,Data/Images/character_images/Dina icon.jpeg,Age: Likely the same age as Ellie (19-21 yrs. ...,"Dina is a resident of the Jackson community, a...",
3,Abby,Data/Images/character_images/Abby icon.jpeg,"Age: Early Twenties, Status: Alive, Occupation...",Abby used to be a Firefly member along with he...,
4,Yara,Data/Images/character_images/Yara icon.jpeg,"Age: 16, Status: Deceased, Occupation: Former ...",Yara is known to be Lev's older sister. She wa...,

In [86]:
def populate_what_happens(character_name, character_df, character_info_df):

  
    character_data_row = character_df[character_df['Character Name'] == character_name]

    
    if not character_data_row.empty and 'Character Information' in character_data_row.columns:
        character_info_data = character_data_row['Character Information'].iloc[0]

 
        if isinstance(character_info_data, str):
            try:
                character_info_data = ast.literal_eval(character_info_data)
            except (ValueError, SyntaxError) as e:
                print(f"Could not evaluate character_info string for {character_name}: {e}")
                character_info_data = {}

     
        if isinstance(character_info_data, dict):
            what_happens_heading = None
            for heading in character_info_data.keys():
                 if "What Happens to" in heading:
                     what_happens_heading = heading
                     break

          
            if what_happens_heading and what_happens_heading in character_info_data:
        
                 content = character_info_data[what_happens_heading]

                
                 if isinstance(content, dict) and 'paragraphs' in content and content['paragraphs']:
                      what_happens_text = content['paragraphs']

          
                      char_info_index = character_info_df[character_info_df['Character name'] == character_name].index
                      if not char_info_index.empty:
                          character_info_df.loc[char_info_index[0], 'What happens to the character'] = what_happens_text
                          print(f"What happens to {character_name} populated successfully.")
                      else:
                          print(f"{character_name}'s row not found in character_info_df DataFrame.")
                 else:
                    print(f"What happens to {character_name} contains an unexpected structure (not paragraphs).")
            else:
                print(f"What happens to heading not found in {character_name}'s Character Info dictionary.")
    else:
        print(f"{character_name}'s row or 'Character Info' column not found in character_df DataFrame.")

In [87]:
for character_name in character_info_df['Character name']:
    populate_what_happens(character_name, character_df, character_info_df)

character_info_df.head()

What happens to Ellie populated successfully.
What happens to Joel populated successfully.
What happens to Dina populated successfully.
What happens to heading not found in Abby's Character Info dictionary.
What happens to Yara populated successfully.
What happens to Nora populated successfully.
What happens to Lev populated successfully.
What happens to Emily populated successfully.
What happens to Jesse populated successfully.
What happens to Tommy populated successfully.
What happens to heading not found in Seth's Character Info dictionary.
What happens to Mel populated successfully.
What happens to Owen populated successfully.
What happens to Manny populated successfully.
What happens to Jordan populated successfully.
What happens to heading not found in Nick's Character Info dictionary.
What happens to Alice populated successfully.
What happens to heading not found in Maria's Character Info dictionary.
What happens to heading not found in Jerry's Character Info dictionary.
What happens to heading not found in Whitney's Character Info dictionary.
What happens to Isaac populated successfully.

,Character name,Character Image,Basic Information,Profile and Backstory,What happens to the character
0,Ellie,Data/Images/character_images/Ellie icon.jpeg,"Age: 19, Status: Alive, Occupation: Jackson Pa...","In The Last of Us 1, Ellie is immune to the Co...",Final Warning:Major spoilers Ahead!You have be...
1,Joel,Data/Images/character_images/Joel icon.jpeg,"Age: Mid 50's, Status: Deceased, Occupation: J...","During the events of the first game, Joel emba...",Final Warning:Major spoilers Ahead!You have be...
2,Dina,Data/Images/character_images/Dina icon.jpeg,Age: Likely the same age as Ellie (19-21 yrs. ...,"Dina is a resident of the Jackson community, a...",WARNING! Might contain some information that i...
3,Abby,Data/Images/character_images/Abby icon.jpeg,"Age: Early Twenties, Status: Alive, Occupation...",Abby used to be a Firefly member along with he...,
4,Yara,Data/Images/character_images/Yara icon.jpeg,"Age: 16, Status: Deceased, Occupation: Former ...",Yara is known to be Lev's older sister. She wa...,Click to View (Contains Spoilers)\nYara can be...

Abby:
The conclusion will happen during the Santa Barbara chapter, where Ellie and Abby meet once again. After The Beach part where Ellie successfully rescues Abby from the Rattlers, they will face off on the beach.

Ellie wanted to finish what she started by killing Abby, but when she is close to drowning Abby on the beach, she remembers Joel's smile, then lets her and Lev leave the beach.

She wanted to end the cycle of revenge by sparing Abby's life. Because if Abby dies, it is most likely that Lev will take upon getting revenge on Ellie, then someone will avenge Ellie's death and so forth. This might be the reason why Ellie lets her live, before going back to the farm.

Seth:
We never find out, what happens to Seth

Nick:
We never find out, what happens to Nick

Maria:
We never find out, what happens to Maria

Jerry:
Died at the end of The Last Of Us Part 1


Whitney:
We never find out, what happens to Whitney

In [88]:
what_happens_manual_data = {
    'Abby': """The conclusion will happen during the Santa Barbara chapter, where Ellie and Abby meet once again. After The Beach part where Ellie successfully rescues Abby from the Rattlers, they will face off on the beach.

Ellie wanted to finish what she started by killing Abby, but when she is close to drowning Abby on the beach, she remembers Joel's smile, then lets her and Lev leave the beach.

She wanted to end the cycle of revenge by sparing Abby's life. Because if Abby dies, it is most likely that Lev will take upon getting revenge on Ellie, then someone will avenge Ellie's death and so forth. This might be the reason why Ellie lets her live, before going back to the farm.""",

    'Seth': "We never find out, what happens to Seth.",

    'Nick': "We never find out, what happens to Nick.",

    'Maria': "We never find out, what happens to Maria.",

    'Jerry': "Died at the end of The Last Of Us Part 1.",

    'Whitney': "We never find out, what happens to Whitney."
}


for character_name, what_happens_text in what_happens_manual_data.items():
    char_index = character_info_df[character_info_df['Character name'] == character_name].index


    if not char_index.empty:
        character_info_df.loc[char_index[0], 'What happens to the character'] = what_happens_text.strip()
        print(f"Manually updated 'What happens to the character' for {character_name}")
    else:
        print(f"Warning: Could not find {character_name} in character_info DataFrame to update manually.")

Manually updated 'What happens to the character' for Abby
Manually updated 'What happens to the character' for Seth
Manually updated 'What happens to the character' for Nick
Manually updated 'What happens to the character' for Maria
Manually updated 'What happens to the character' for Jerry
Manually updated 'What happens to the character' for Whitney

In [91]:
phrases_to_remove_character_info = [
    'Click to View',
    'Click to View (Contains Spoilers)',
    '(Contains Spoilers)'
]

for index, row in character_info_df.iterrows():
    text = row['What happens to the character']
    if isinstance(text, str): 
        for phrase in phrases_to_remove_character_info:
            text = text.replace(phrase, '').strip()
        character_info_df.loc[index, 'What happens to the character'] = text

In [92]:
character_info_df.to_csv('Character Information.csv', index=False)

## Trophy EDA/Cleaning

In [103]:
Trophy_df = pd.read_csv('../Data/Trophies.csv')

Trophy_df.head()

,Trophy Category,Image URL,Title,Description
0,Platinum Trophy Guide,https://img.game8.co/3243707/9785cef1a5b2d639e...,Every Last One of Them,Collect all trophies
1,Gold Trophies Guide,https://img.game8.co/3243708/0677172e17d90a592...,What I Had to Do,Complete the story
2,Gold Trophies Guide,https://img.game8.co/3243708/0677172e17d90a592...,Survival Expert,Learn all player upgrades
3,Gold Trophies Guide,https://img.game8.co/3243708/0677172e17d90a592...,Arms Master,Fully upgrade all weapons
4,Gold Trophies Guide,https://img.game8.co/3243708/0677172e17d90a592...,Archivist,Find all artifacts and journal entries

In [104]:
def update_trophy_image_url(row):
    category = row['Trophy Category'].split(' ')[0] 

    if category == 'Hidden':
        category = 'Bronze' 

    image_path = f"../Data/Images/trophy_images/{category}.jpg"

    return image_path

Trophy_df['Image URL'] = Trophy_df.apply(update_trophy_image_url, axis=1)

Trophy_df.head()

,Trophy Category,Image URL,Title,Description
0,Platinum Trophy Guide,../Data/Images/trophy_images/Platinum.jpg,Every Last One of Them,Collect all trophies
1,Gold Trophies Guide,../Data/Images/trophy_images/Gold.jpg,What I Had to Do,Complete the story
2,Gold Trophies Guide,../Data/Images/trophy_images/Gold.jpg,Survival Expert,Learn all player upgrades
3,Gold Trophies Guide,../Data/Images/trophy_images/Gold.jpg,Arms Master,Fully upgrade all weapons
4,Gold Trophies Guide,../Data/Images/trophy_images/Gold.jpg,Archivist,Find all artifacts and journal entries

In [105]:
Trophy_df.to_csv('Trophy Information.csv', index=False)

## Safe EDA/Cleaning

In [93]:
Safecodes_df = pd.read_csv('../Data/Safecode.csv')

Safecodes_df.head()

,Chapter,Location,Combination/Code,URL,Images,Paragraphs,Headings,Steps to Safe
0,Jackson - Patrol,Super Market,07-20-13,https://game8.co/games/Last-of-Us-2/archives/2...,['https://img.game8.co/3252183/b8d35c36c932601...,"['', 'This guide will show you how to open the...","{'hl_1': 'Supermarket Safe Location', 'hl_2': ...","[{'heading': 'Finding the Code', 'paragraphs':..."
1,Seattle Day 1 - Downtown,Bank Vault,60-23-06,https://game8.co/games/Last-of-Us-2/archives/2...,['https://img.game8.co/3252020/ffaf25313126fdb...,"['', 'Downtown Seattle in The Last of Us 2 is ...","{'hl_1': 'Bank Vault Location', 'hl_2': 'Bank ...","[{'heading': 'Finding the Bank', 'paragraphs':..."
2,Seattle Day 1 - Downtown,Courthouse,86-07-22,https://game8.co/games/Last-of-Us-2/archives/2...,['https://img.game8.co/3252906/4c524880161ae19...,"['', 'This guide will show you how to unlock t...","{'hl_1': 'Courthouse Safe Location', 'hl_2': '...","[{'heading': 'Finding the Code', 'paragraphs':..."
3,Seattle Day 1 - Downtown,West Gate 2,04-51,https://game8.co/games/Last-of-Us-2/archives/2...,['https://img.game8.co/3252837/e9638d1add0564b...,['This is a guide to the Checkpoint Gate Codes...,"{'hl_1': 'Downtown Seattle Gate Codes', 'hl_2'...","[{'heading': 'Where to Find the Gate Codes', '..."
4,Seattle Day 1 - Capitol Hill,Thrift Store,55-01-33,https://game8.co/games/Last-of-Us-2/archives/2...,['https://img.game8.co/3252221/3f924449f3a3c12...,"['', ""This guide will show you how to unlock t...","{'hl_1': 'Thrift Store Safe Location', 'hl_2':...","[{'heading': 'Hint 1', 'paragraphs': ['From th..."

In [94]:
Safecodes_df = Safecodes_df.drop(columns=['URL'])
Safecodes_df.head()

,Chapter,Location,Combination/Code,Images,Paragraphs,Headings,Steps to Safe
0,Jackson - Patrol,Super Market,07-20-13,['https://img.game8.co/3252183/b8d35c36c932601...,"['', 'This guide will show you how to open the...","{'hl_1': 'Supermarket Safe Location', 'hl_2': ...","[{'heading': 'Finding the Code', 'paragraphs':..."
1,Seattle Day 1 - Downtown,Bank Vault,60-23-06,['https://img.game8.co/3252020/ffaf25313126fdb...,"['', 'Downtown Seattle in The Last of Us 2 is ...","{'hl_1': 'Bank Vault Location', 'hl_2': 'Bank ...","[{'heading': 'Finding the Bank', 'paragraphs':..."
2,Seattle Day 1 - Downtown,Courthouse,86-07-22,['https://img.game8.co/3252906/4c524880161ae19...,"['', 'This guide will show you how to unlock t...","{'hl_1': 'Courthouse Safe Location', 'hl_2': '...","[{'heading': 'Finding the Code', 'paragraphs':..."
3,Seattle Day 1 - Downtown,West Gate 2,04-51,['https://img.game8.co/3252837/e9638d1add0564b...,['This is a guide to the Checkpoint Gate Codes...,"{'hl_1': 'Downtown Seattle Gate Codes', 'hl_2'...","[{'heading': 'Where to Find the Gate Codes', '..."
4,Seattle Day 1 - Capitol Hill,Thrift Store,55-01-33,['https://img.game8.co/3252221/3f924449f3a3c12...,"['', ""This guide will show you how to unlock t...","{'hl_1': 'Thrift Store Safe Location', 'hl_2':...","[{'heading': 'Hint 1', 'paragraphs': ['From th..."

In [95]:
safe_codes_df = pd.DataFrame({
    'Chapter': Safecodes_df['Chapter'],
    'Location': Safecodes_df['Location'],
    'Safe Code': Safecodes_df['Combination/Code']

})
safe_codes_df['Safe Image'] = ''
safe_codes_df['Finding the Safe Code'] = ''

In [96]:
safe_codes_df.head()

,Chapter,Location,Safe Code,Safe Image,Finding the Safe Code
0,Jackson - Patrol,Super Market,07-20-13,,
1,Seattle Day 1 - Downtown,Bank Vault,60-23-06,,
2,Seattle Day 1 - Downtown,Courthouse,86-07-22,,
3,Seattle Day 1 - Downtown,West Gate 2,04-51,,
4,Seattle Day 1 - Capitol Hill,Thrift Store,55-01-33,,

In [98]:
def update_safe_image_url(row):
    location_name = row['Location']
    image_path = f"../Data/Images/safe_images/{location_name}.jpg"
    return image_path

safe_codes_df['Safe Image'] = safe_codes_df.apply(update_safe_image_url, axis=1)

safe_codes_df.head()

,Chapter,Location,Safe Code,Safe Image,Finding the Safe Code
0,Jackson - Patrol,Super Market,07-20-13,../Data/Images/safe_images/Super Market.jpg,
1,Seattle Day 1 - Downtown,Bank Vault,60-23-06,../Data/Images/safe_images/Bank Vault.jpg,
2,Seattle Day 1 - Downtown,Courthouse,86-07-22,../Data/Images/safe_images/Courthouse.jpg,
3,Seattle Day 1 - Downtown,West Gate 2,04-51,../Data/Images/safe_images/West Gate 2.jpg,
4,Seattle Day 1 - Capitol Hill,Thrift Store,55-01-33,../Data/Images/safe_images/Thrift Store.jpg,

In [99]:
def process_safe_steps_and_images(row):
    steps_data_str = row['Steps to Safe']
    processed_text = ""

    try:
        steps_data = ast.literal_eval(steps_data_str)

        if isinstance(steps_data, list):
            all_paragraphs = []
            for step in steps_data:
                if isinstance(step, dict) and 'paragraphs' in step:
                    if isinstance(step['paragraphs'], list):
                        all_paragraphs.extend(step['paragraphs'])
                    elif isinstance(step['paragraphs'], str):
                        all_paragraphs.append(step['paragraphs'])

            processed_text = " ".join(all_paragraphs)

    except (ValueError, SyntaxError) as e:
        print(f"Error processing steps for {row['Location']}: {e}")
        processed_text = ""

    return processed_text

safe_codes_df['Finding the Safe Code'] = Safecodes_df.apply(process_safe_steps_and_images, axis=1)

safe_codes_df.head()

,Chapter,Location,Safe Code,Safe Image,Finding the Safe Code
0,Jackson - Patrol,Super Market,07-20-13,../Data/Images/safe_images/Super Market.jpg,"First, you will want to look for a note that i..."
1,Seattle Day 1 - Downtown,Bank Vault,60-23-06,../Data/Images/safe_images/Bank Vault.jpg,"In chapter 2 ( Seattle Day 1 - Downtown ), onc..."
2,Seattle Day 1 - Downtown,Courthouse,86-07-22,../Data/Images/safe_images/Courthouse.jpg,This one will be really easy. Once you enter t...
3,Seattle Day 1 - Downtown,West Gate 2,04-51,../Data/Images/safe_images/West Gate 2.jpg,The gate codes can be found in the first porta...
4,Seattle Day 1 - Capitol Hill,Thrift Store,55-01-33,../Data/Images/safe_images/Thrift Store.jpg,"From the back room, there will be a door that ..."

In [100]:
locker_room_description = """In Chapter 2: Seattle Day 1 - The Tunnels, you will come across two rooms to the right of a long narrow pass in the tunnel. In one of those rooms, there will be a scrap of paper with a hint about where the code for the locked door to the locker room is.In the vending machine there is a red soda can that has a note taped to it that has the first 3 digits for the locker room lock. Despite being able to get these first three digits, there is no way to find the last two digits.
The Lock only has 5 buttons which must all be pressed, and no number can be repeated. Since you have the first 3 numbers of 1-5-2 there are only two other possible combinations to try.Once inside the locker room you will find scrap, ammo, and supplements."""

locker_room_index = safe_codes_df[safe_codes_df['Location'] == 'Locker Room'].index

if not locker_room_index.empty:
    safe_codes_df.loc[locker_room_index[0], 'Finding the Safe Code'] = locker_room_description.strip()
    print("Description for Locker Room updated successfully.")
else:
    print("Warning: Could not find 'Locker Room' in safe_codes_df to update.")

Description for Locker Room updated successfully.

In [101]:
def clean_finding_safe_code(text):
    phrases_to_remove = [
        "Click to see the Safe Combination ",
        "Weapons List | Where to Find All Weapons",
        "Pump Shotgun: Location and Best Upgrades"
    ]
    if isinstance(text, str):
        for phrase in phrases_to_remove:
            text = text.replace(phrase, '')
        # Replace multiple spaces with a single space
        text = re.sub(r'\s+', ' ', text).strip()
        return text
    return text

safe_codes_df['Finding the Safe Code'] = safe_codes_df['Finding the Safe Code'].apply(clean_finding_safe_code)

safe_codes_df.head()

,Chapter,Location,Safe Code,Safe Image,Finding the Safe Code
0,Jackson - Patrol,Super Market,07-20-13,../Data/Images/safe_images/Super Market.jpg,"First, you will want to look for a note that i..."
1,Seattle Day 1 - Downtown,Bank Vault,60-23-06,../Data/Images/safe_images/Bank Vault.jpg,"In chapter 2 ( Seattle Day 1 - Downtown ), onc..."
2,Seattle Day 1 - Downtown,Courthouse,86-07-22,../Data/Images/safe_images/Courthouse.jpg,This one will be really easy. Once you enter t...
3,Seattle Day 1 - Downtown,West Gate 2,04-51,../Data/Images/safe_images/West Gate 2.jpg,The gate codes can be found in the first porta...
4,Seattle Day 1 - Capitol Hill,Thrift Store,55-01-33,../Data/Images/safe_images/Thrift Store.jpg,"From the back room, there will be a door that ..."

In [102]:
safe_codes_df.to_csv('Safecodes Information.csv', index=False)